// Code generated by Thrift Compiler (0.23.0). DO NOT EDIT.

package protoservice

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"iter"
	"log/slog"
	"regexp"
	"strings"
	"time"
)

// (needed to ensure safety because of naive import list construction.)
var _ = bytes.Equal
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = iter.Pull[int]
var _ = slog.Log
var _ = time.Now
var _ = thrift.ZERO

// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

// Attributes:
//   - Type
//   - Content
//   - ShardingID
//   - Trace
type ProtoRequest struct {
	Type       int32  `thrift:"type,1,required" db:"type" json:"type"`
	Content    []byte `thrift:"content,2,required" db:"content" json:"content"`
	ShardingID int64  `thrift:"sharding_id,3,required" db:"sharding_id" json:"sharding_id"`
	Trace      []byte `thrift:"trace,4" db:"trace" json:"trace,omitempty"`
}

func NewProtoRequest() *ProtoRequest {
	return &ProtoRequest{}
}

func (p *ProtoRequest) GetType() int32 {
	return p.Type
}

func (p *ProtoRequest) GetContent() []byte {
	return p.Content
}

func (p *ProtoRequest) GetShardingID() int64 {
	return p.ShardingID
}

var ProtoRequest_Trace_DEFAULT []byte

func (p *ProtoRequest) GetTrace() []byte {
	return p.Trace
}

func (p *ProtoRequest) IsSetTrace() bool {
	return p.Trace != nil
}

func (p *ProtoRequest) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetType bool = false
	var issetContent bool = false
	var issetShardingID bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
				issetType = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
				issetContent = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
				issetShardingID = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetType {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Type is not set"))
	}
	if !issetContent {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Content is not set"))
	}
	if !issetShardingID {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field ShardingID is not set"))
	}
	return nil
}

func (p *ProtoRequest) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Type = v
	}
	return nil
}

func (p *ProtoRequest) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Content = v
	}
	return nil
}

func (p *ProtoRequest) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.ShardingID = v
	}
	return nil
}

func (p *ProtoRequest) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(ctx); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.Trace = v
	}
	return nil
}

func (p *ProtoRequest) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "ProtoRequest"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField3(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField4(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ProtoRequest) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "type", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:type: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Type)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.type (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:type: ", p), err)
	}
	return err
}

func (p *ProtoRequest) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "content", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:content: ", p), err)
	}
	if err := oprot.WriteBinary(ctx, p.Content); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.content (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:content: ", p), err)
	}
	return err
}

func (p *ProtoRequest) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "sharding_id", thrift.I64, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:sharding_id: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.ShardingID)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.sharding_id (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:sharding_id: ", p), err)
	}
	return err
}

func (p *ProtoRequest) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetTrace() {
		if err := oprot.WriteFieldBegin(ctx, "trace", thrift.STRING, 4); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:trace: ", p), err)
		}
		if err := oprot.WriteBinary(ctx, p.Trace); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.trace (4) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 4:trace: ", p), err)
		}
	}
	return err
}

func (p *ProtoRequest) Equals(other *ProtoRequest) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Type != other.Type {
		return false
	}
	if bytes.Compare(p.Content, other.Content) != 0 {
		return false
	}
	if p.ShardingID != other.ShardingID {
		return false
	}
	if bytes.Compare(p.Trace, other.Trace) != 0 {
		return false
	}
	return true
}

func (p *ProtoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProtoRequest(%+v)", *p)
}

func (p *ProtoRequest) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*protoservice.ProtoRequest",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*ProtoRequest)(nil)

func (p *ProtoRequest) Validate() error {
	return nil
}

// Attributes:
//   - Result_
//   - Type
//   - Content
//   - Trace
type ProtoReply struct {
	Result_ int64  `thrift:"result,1,required" db:"result" json:"result"`
	Type    int32  `thrift:"type,2,required" db:"type" json:"type"`
	Content []byte `thrift:"content,3,required" db:"content" json:"content"`
	Trace   []byte `thrift:"trace,4" db:"trace" json:"trace,omitempty"`
}

func NewProtoReply() *ProtoReply {
	return &ProtoReply{}
}

func (p *ProtoReply) GetResult_() int64 {
	return p.Result_
}

func (p *ProtoReply) GetType() int32 {
	return p.Type
}

func (p *ProtoReply) GetContent() []byte {
	return p.Content
}

var ProtoReply_Trace_DEFAULT []byte

func (p *ProtoReply) GetTrace() []byte {
	return p.Trace
}

func (p *ProtoReply) IsSetTrace() bool {
	return p.Trace != nil
}

func (p *ProtoReply) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetResult_ bool = false
	var issetType bool = false
	var issetContent bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
				issetResult_ = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
				issetType = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
				issetContent = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetResult_ {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Result_ is not set"))
	}
	if !issetType {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Type is not set"))
	}
	if !issetContent {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Content is not set"))
	}
	return nil
}

func (p *ProtoReply) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Result_ = v
	}
	return nil
}

func (p *ProtoReply) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Type = v
	}
	return nil
}

func (p *ProtoReply) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.Content = v
	}
	return nil
}

func (p *ProtoReply) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(ctx); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.Trace = v
	}
	return nil
}

func (p *ProtoReply) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "ProtoReply"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField3(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField4(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ProtoReply) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "result", thrift.I64, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:result: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.Result_)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.result (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:result: ", p), err)
	}
	return err
}

func (p *ProtoReply) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "type", thrift.I32, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:type: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Type)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.type (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:type: ", p), err)
	}
	return err
}

func (p *ProtoReply) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "content", thrift.STRING, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:content: ", p), err)
	}
	if err := oprot.WriteBinary(ctx, p.Content); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.content (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:content: ", p), err)
	}
	return err
}

func (p *ProtoReply) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetTrace() {
		if err := oprot.WriteFieldBegin(ctx, "trace", thrift.STRING, 4); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:trace: ", p), err)
		}
		if err := oprot.WriteBinary(ctx, p.Trace); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.trace (4) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 4:trace: ", p), err)
		}
	}
	return err
}

func (p *ProtoReply) Equals(other *ProtoReply) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Result_ != other.Result_ {
		return false
	}
	if p.Type != other.Type {
		return false
	}
	if bytes.Compare(p.Content, other.Content) != 0 {
		return false
	}
	if bytes.Compare(p.Trace, other.Trace) != 0 {
		return false
	}
	return true
}

func (p *ProtoReply) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProtoReply(%+v)", *p)
}

func (p *ProtoReply) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*protoservice.ProtoReply",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*ProtoReply)(nil)

func (p *ProtoReply) Validate() error {
	return nil
}

type ProtoRpcService interface {
	// Parameters:
	//  - Msg
	//
	DealTwowayMessage(ctx context.Context, msg *ProtoRequest) (_r *ProtoReply, _err error)
	// Parameters:
	//  - Msg
	//
	DealOnewayMessage(ctx context.Context, msg *ProtoRequest) (_err error)
}

type ProtoRpcServiceClient struct {
	c    thrift.TClient
	meta thrift.ResponseMeta
}

func NewProtoRpcServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *ProtoRpcServiceClient {
	return &ProtoRpcServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewProtoRpcServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *ProtoRpcServiceClient {
	return &ProtoRpcServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewProtoRpcServiceClient(c thrift.TClient) *ProtoRpcServiceClient {
	return &ProtoRpcServiceClient{
		c: c,
	}
}

func (p *ProtoRpcServiceClient) Client_() thrift.TClient {
	return p.c
}

func (p *ProtoRpcServiceClient) LastResponseMeta_() thrift.ResponseMeta {
	return p.meta
}

func (p *ProtoRpcServiceClient) SetLastResponseMeta_(meta thrift.ResponseMeta) {
	p.meta = meta
}

// Parameters:
//   - Msg
func (p *ProtoRpcServiceClient) DealTwowayMessage(ctx context.Context, msg *ProtoRequest) (_r *ProtoReply, _err error) {
	var _args0 ProtoRpcServiceDealTwowayMessageArgs
	_args0.Msg = msg
	var _result2 ProtoRpcServiceDealTwowayMessageResult
	var _meta1 thrift.ResponseMeta
	_meta1, _err = p.Client_().Call(ctx, "dealTwowayMessage", &_args0, &_result2)
	p.SetLastResponseMeta_(_meta1)
	if _err != nil {
		return
	}
	if _ret3 := _result2.GetSuccess(); _ret3 != nil {
		return _ret3, nil
	}
	return nil, thrift.NewTApplicationException(thrift.MISSING_RESULT, "dealTwowayMessage failed: unknown result")
}

// Parameters:
//   - Msg
func (p *ProtoRpcServiceClient) DealOnewayMessage(ctx context.Context, msg *ProtoRequest) (_err error) {
	var _args4 ProtoRpcServiceDealOnewayMessageArgs
	_args4.Msg = msg
	p.SetLastResponseMeta_(thrift.ResponseMeta{})
	if _, err := p.Client_().Call(ctx, "dealOnewayMessage", &_args4, nil); err != nil {
		return err
	}
	return nil
}

type ProtoRpcServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      ProtoRpcService
}

func (p *ProtoRpcServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *ProtoRpcServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *ProtoRpcServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewProtoRpcServiceProcessor(handler ProtoRpcService) *ProtoRpcServiceProcessor {

	self5 := &ProtoRpcServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self5.processorMap["dealTwowayMessage"] = &protoRpcServiceProcessorDealTwowayMessage{handler: handler}
	self5.processorMap["dealOnewayMessage"] = &protoRpcServiceProcessorDealOnewayMessage{handler: handler}
	return self5
}

func (p *ProtoRpcServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err2 := iprot.ReadMessageBegin(ctx)
	if err2 != nil {
		return false, thrift.WrapTException(err2)
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(ctx, thrift.STRUCT)
	iprot.ReadMessageEnd(ctx)
	x6 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(ctx, name, thrift.EXCEPTION, seqId)
	x6.Write(ctx, oprot)
	oprot.WriteMessageEnd(ctx)
	oprot.Flush(ctx)
	return false, x6
}

type protoRpcServiceProcessorDealTwowayMessage struct {
	handler ProtoRpcService
}

func (p *protoRpcServiceProcessorDealTwowayMessage) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err7 thrift.TException
	args := ProtoRpcServiceDealTwowayMessageArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "dealTwowayMessage", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := ProtoRpcServiceDealTwowayMessageResult{}
	if retval, err2 := p.handler.DealTwowayMessage(ctx, args.Msg); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		if errors.Is(err2, thrift.ErrAbandonRequest) {
			return false, &thrift.ProcessorError{
				WriteError:    thrift.WrapTException(err2),
				EndpointError: err,
			}
		}
		if errors.Is(err2, context.Canceled) {
			if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err3),
					EndpointError: err,
				}
			}
		}
		_exc8 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing dealTwowayMessage: "+err2.Error())
		if err2 := oprot.WriteMessageBegin(ctx, "dealTwowayMessage", thrift.EXCEPTION, seqId); err2 != nil {
			_write_err7 = thrift.WrapTException(err2)
		}
		if err2 := _exc8.Write(ctx, oprot); _write_err7 == nil && err2 != nil {
			_write_err7 = thrift.WrapTException(err2)
		}
		if err2 := oprot.WriteMessageEnd(ctx); _write_err7 == nil && err2 != nil {
			_write_err7 = thrift.WrapTException(err2)
		}
		if err2 := oprot.Flush(ctx); _write_err7 == nil && err2 != nil {
			_write_err7 = thrift.WrapTException(err2)
		}
		if _write_err7 != nil {
			return false, &thrift.ProcessorError{
				WriteError:    _write_err7,
				EndpointError: err,
			}
		}
		return true, err
	} else {
		result.Success = retval
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "dealTwowayMessage", thrift.REPLY, seqId); err2 != nil {
		_write_err7 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err7 == nil && err2 != nil {
		_write_err7 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err7 == nil && err2 != nil {
		_write_err7 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err7 == nil && err2 != nil {
		_write_err7 = thrift.WrapTException(err2)
	}
	if _write_err7 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err7,
			EndpointError: err,
		}
	}
	return true, err
}

type protoRpcServiceProcessorDealOnewayMessage struct {
	handler ProtoRpcService
}

func (p *protoRpcServiceProcessorDealOnewayMessage) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := ProtoRpcServiceDealOnewayMessageArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	_ = tickerCancel

	if err2 := p.handler.DealOnewayMessage(ctx, args.Msg); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
	}
	tickerCancel()
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//   - Msg
type ProtoRpcServiceDealTwowayMessageArgs struct {
	Msg *ProtoRequest `thrift:"msg,1" db:"msg" json:"msg"`
}

func NewProtoRpcServiceDealTwowayMessageArgs() *ProtoRpcServiceDealTwowayMessageArgs {
	return &ProtoRpcServiceDealTwowayMessageArgs{}
}

var ProtoRpcServiceDealTwowayMessageArgs_Msg_DEFAULT *ProtoRequest

func (p *ProtoRpcServiceDealTwowayMessageArgs) GetMsg() *ProtoRequest {
	if !p.IsSetMsg() {
		return ProtoRpcServiceDealTwowayMessageArgs_Msg_DEFAULT
	}
	return p.Msg
}

func (p *ProtoRpcServiceDealTwowayMessageArgs) IsSetMsg() bool {
	return p.Msg != nil
}

func (p *ProtoRpcServiceDealTwowayMessageArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *ProtoRpcServiceDealTwowayMessageArgs) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Msg = &ProtoRequest{}
	if err := p.Msg.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Msg), err)
	}
	return nil
}

func (p *ProtoRpcServiceDealTwowayMessageArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "dealTwowayMessage_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ProtoRpcServiceDealTwowayMessageArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "msg", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:msg: ", p), err)
	}
	if err := p.Msg.Write(ctx, oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Msg), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:msg: ", p), err)
	}
	return err
}

func (p *ProtoRpcServiceDealTwowayMessageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProtoRpcServiceDealTwowayMessageArgs(%+v)", *p)
}

func (p *ProtoRpcServiceDealTwowayMessageArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*protoservice.ProtoRpcServiceDealTwowayMessageArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*ProtoRpcServiceDealTwowayMessageArgs)(nil)

// Attributes:
//   - Success
type ProtoRpcServiceDealTwowayMessageResult struct {
	Success *ProtoReply `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewProtoRpcServiceDealTwowayMessageResult() *ProtoRpcServiceDealTwowayMessageResult {
	return &ProtoRpcServiceDealTwowayMessageResult{}
}

var ProtoRpcServiceDealTwowayMessageResult_Success_DEFAULT *ProtoReply

func (p *ProtoRpcServiceDealTwowayMessageResult) GetSuccess() *ProtoReply {
	if !p.IsSetSuccess() {
		return ProtoRpcServiceDealTwowayMessageResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ProtoRpcServiceDealTwowayMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProtoRpcServiceDealTwowayMessageResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField0(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *ProtoRpcServiceDealTwowayMessageResult) ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
	p.Success = &ProtoReply{}
	if err := p.Success.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *ProtoRpcServiceDealTwowayMessageResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "dealTwowayMessage_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ProtoRpcServiceDealTwowayMessageResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *ProtoRpcServiceDealTwowayMessageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProtoRpcServiceDealTwowayMessageResult(%+v)", *p)
}

func (p *ProtoRpcServiceDealTwowayMessageResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*protoservice.ProtoRpcServiceDealTwowayMessageResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*ProtoRpcServiceDealTwowayMessageResult)(nil)

// Attributes:
//   - Msg
type ProtoRpcServiceDealOnewayMessageArgs struct {
	Msg *ProtoRequest `thrift:"msg,1" db:"msg" json:"msg"`
}

func NewProtoRpcServiceDealOnewayMessageArgs() *ProtoRpcServiceDealOnewayMessageArgs {
	return &ProtoRpcServiceDealOnewayMessageArgs{}
}

var ProtoRpcServiceDealOnewayMessageArgs_Msg_DEFAULT *ProtoRequest

func (p *ProtoRpcServiceDealOnewayMessageArgs) GetMsg() *ProtoRequest {
	if !p.IsSetMsg() {
		return ProtoRpcServiceDealOnewayMessageArgs_Msg_DEFAULT
	}
	return p.Msg
}

func (p *ProtoRpcServiceDealOnewayMessageArgs) IsSetMsg() bool {
	return p.Msg != nil
}

func (p *ProtoRpcServiceDealOnewayMessageArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *ProtoRpcServiceDealOnewayMessageArgs) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Msg = &ProtoRequest{}
	if err := p.Msg.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Msg), err)
	}
	return nil
}

func (p *ProtoRpcServiceDealOnewayMessageArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "dealOnewayMessage_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ProtoRpcServiceDealOnewayMessageArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "msg", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:msg: ", p), err)
	}
	if err := p.Msg.Write(ctx, oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Msg), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:msg: ", p), err)
	}
	return err
}

func (p *ProtoRpcServiceDealOnewayMessageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProtoRpcServiceDealOnewayMessageArgs(%+v)", *p)
}

func (p *ProtoRpcServiceDealOnewayMessageArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*protoservice.ProtoRpcServiceDealOnewayMessageArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*ProtoRpcServiceDealOnewayMessageArgs)(nil)
